apiVersion: v1
items:
- apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: HelmRepository
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"source.toolkit.fluxcd.io/v1beta2","kind":"HelmRepository","metadata":{"annotations":{},"name":"xl-app-store","namespace":"default"},"spec":{"interval":"1m","secretRef":{"name":"xl-app-store-secret"},"url":"https://10.50.166.201/chartrepo/xl-app-store"}}
      resourcebinding.karmada.io/name: xl-app-store-helmrepository
      resourcebinding.karmada.io/namespace: default
      resourcetemplate.karmada.io/uid: eb98b8f7-5ebd-494e-813e-5c4e07bfa6a4
    creationTimestamp: "2022-12-20T09:38:15Z"
    finalizers:
    - finalizers.fluxcd.io
    generation: 1
    labels:
      propagationpolicy.karmada.io/name: xl-app-store-cks1-helmrepository-pp
      propagationpolicy.karmada.io/namespace: default
      resourcebinding.karmada.io/key: 75bc8fd6b6
      work.karmada.io/name: xl-app-store-75bc8fd6b6
      work.karmada.io/namespace: karmada-es-cn-west-1-a-eks-1
    name: xl-app-store
    namespace: default
    resourceVersion: "6216584"
    selfLink: /apis/source.toolkit.fluxcd.io/v1beta2/namespaces/default/helmrepositories/xl-app-store
    uid: 26191284-c6dd-4d20-86e1-3e0e97ec5d25
  spec:
    interval: 1m
    provider: generic
    secretRef:
      name: xl-app-store-secret
    timeout: 60s
    url: https://10.50.166.201/chartrepo/xl-app-store
  status:
    artifact:
      checksum: b4210b08b55c158e5f31300c6cba7571342ec9fef8ae9f72291979c57354befa
      lastUpdateTime: "2022-12-20T09:38:16Z"
      path: helmrepository/default/xl-app-store/index-b4210b08b55c158e5f31300c6cba7571342ec9fef8ae9f72291979c57354befa.yaml
      revision: b4210b08b55c158e5f31300c6cba7571342ec9fef8ae9f72291979c57354befa
      size: 973
      url: http://source-controller.flux-system.svc.cluster.local./helmrepository/default/xl-app-store/index-b4210b08b55c158e5f31300c6cba7571342ec9fef8ae9f72291979c57354befa.yaml
    conditions:
    - lastTransitionTime: "2022-12-20T09:38:16Z"
      message: stored artifact for revision 'b4210b08b55c158e5f31300c6cba7571342ec9fef8ae9f72291979c57354befa'
      observedGeneration: 1
      reason: Succeeded
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-12-20T09:38:16Z"
      message: stored artifact for revision 'b4210b08b55c158e5f31300c6cba7571342ec9fef8ae9f72291979c57354befa'
      observedGeneration: 1
      reason: Succeeded
      status: "True"
      type: ArtifactInStorage
    observedGeneration: 1
    url: http://source-controller.flux-system.svc.cluster.local./helmrepository/default/xl-app-store/index.yaml
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
